### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by johnLegasse** [awesome-labs/LFLoginController#14]
Function forgotPasswordTapped doesn't pass any information we can work on to reset the password, the strict minimum should be the email account for example.

LFLoginController.swift Line 22
`
func forgotPasswordTapped()
`
Should be : 
`
func forgotPasswordTapped(email: String)
`

Best Regards

**Comment by lfarah** [comment]
Hey @darktanker89, sorry for the delay... I just saw this issue!

Really thanks for giving that idea. Implementing right now!

**Comment by lfarah** [comment]
🚀  LFLoginController (0.2.8) successfully published to CocoaPods 👍 

@darktanker89
