### ISSUE TITLE
support swift 3/4 ?

### ISSUE THREAD

**Issue by maxiplux** [awesome-labs/LFLoginController#18]
Amazing project my friends , please would be possible know if work with swift 3 or swift 4 ? .
thanks for this amazing work

**Comment by lfarah** [comment]
Hey @maxiplux, thanks for using LFLoginController!
I believe I already updated it to Swift 4.
1. Are you using CocoaPods? If so,  could you try to do the following:
pod 'LFLoginController', :git => 'https://github.com/awesome-labs/LFLoginController.git'

**Comment by lfarah** [comment]
Hey @maxiplux, thanks for using LFLoginController!
I believe I already updated it to Swift 4.
1. Are you using CocoaPods? If so,  could you try to do the following:
pod 'LFLoginController', :git => 'https://github.com/awesome-labs/LFLoginController.git'

**Comment by lfarah** [comment]
I just pushed 0.3 version which is the LFLoginController in Swift 4. Feel free to reopen if there are any problems
